### ISSUE TITLE
Should stacked column chart legend be re-ordered?

### ISSUE THREAD

**Issue by jtrim-ons** [ONSvisual/Charts#115]
I'm not confident that there's any need for a change, but thought it might be worth raising the question...

In the stacked column chart, it takes a bit of effort to match the column colours with the legend colours, because the legend is horizontal and in reverse order:
![image](https://github.com/ONSvisual/Charts/assets/79704945/2deab6eb-a348-4824-8e07-f64c8847150e)

I was wondering if it would be good to do something like the image below instead? To me this seems easier to read. It has the disadvantage of being taller though.
![image](https://github.com/ONSvisual/Charts/assets/79704945/1312cb3d-bcdc-4224-8ff1-fb341563414a)

@incontrolapps I feel like we discussed something like this recently?

**Comment by MikeLister** [comment]
Simple solution would be to use `stackOrderReverse` as the default: 
![image](https://github.com/ONSvisual/Charts/assets/131891138/24cc7b19-5c4d-453b-a87e-391257d966ba)

**Comment by jtrim-ons** [comment]
That sounds like a good plan. Unless there's some reason why you'd want the first category at the bottom when creating a chart??

**Comment by jtrim-ons** [comment]
This was just published today, which seems like a great guide: https://blog.datawrapper.de/color-keys-for-data-visualizations/. Among other things, it suggests laying out the key in a grid.
