### ISSUE TITLE
Bar charts can't handle negative values

### ISSUE THREAD

**Issue by MikeLister** [ONSvisual/Charts#164]
Fixed here: https://fa1rvwwsxx343.ons.statistics.gov.uk/MikeL/new-templates/bar-chart-horizontal-sm/

Need to check across the templates, bars and columns

**Comment by broadpeter** [comment]
Can this be updated even if just for bars (not columns? I just made the same tweak to the template for something I'm working on and hadn't seen this

**Comment by MikeLister** [comment]
Fixed by @jvwigs for dropdown bars here https://github.com/ONSvisual/Charts/commit/fac9ec136e68c06b1e60dbbec569af6831ab1b22
I'll see if I can sort this for the rest of the templates tomorrow

**Comment by MikeLister** [comment]
Fixed across bar chart templates f5a61bc18e1889ce2dc19bc79d0dacbc8ede597c
Still need to check columns
