### ISSUE TITLE
Allow 'free' axes on small multiples

### ISSUE THREAD

**Issue by rcatlord** [ONSvisual/Charts#209]
Creating small multiple line charts with independent scales would be really helpful. It would be an alternative to indexing. [Datawrapper](https://blog.datawrapper.de/small-multiple-line-charts) have some design tips and there is guidance on faceting with free scales in [ggplot2](https://ggplot2-book.org/facet.html#sec-controlling-scales) in Wickham et al. (3rd edition).

**Comment by MikeLister** [comment]
Closed with https://github.com/ONSvisual/Charts/commit/b5d133da6d107fff16c258f77404faacf07202f0
