### ISSUE TITLE
Update range/dot plot with alternative shape for accessibility (diamond)

### ISSUE THREAD

**Issue by broadpeter** [ONSvisual/Charts#237]
see dvc2284 fig 12

**Comment by henryjameslau** [comment]
![image](https://github.com/user-attachments/assets/e7155cf8-9b39-47b3-a59f-38692d9e7afd)
From [Jewish identity](https://www.ons.gov.uk/peoplepopulationandcommunity/culturalidentity/religion/articles/jewishidentityenglandandwales/census2021)
