### ISSUE TITLE
Small multiple line charts can be a mess

### ISSUE THREAD

**Issue by broadpeter** [ONSvisual/Charts#254]
![image](https://github.com/ONSvisual/Charts/assets/41958615/85124399-d050-4bba-8b7a-180f1eede5b4)

**Comment by MikeLister** [comment]
Fixed the x-axis ticks here f118d2aa855f18133718f56a04b28af55e28c1de 
The weirdness with the y-axes is to do with the vis having a scroll bar - something I've investigated but, essentially we don't need to fix it as none of our vis should have a scroll bar, thanks to pym!
