### ISSUE TITLE
Aspect ratio not working

### ISSUE THREAD

**Issue by broadpeter** [ONSvisual/Charts#258]
Line chart (and potentially other charts) has an aspect ratio setting in config but this is not referenced in script.
Instead height is hard coded in script and same for different chart widths leading to poorly proportioned charts on certain sizes, esp mobile

**Comment by sam-ctrl** [comment]
This is still an issue, for the line chart the height is fixed at 400 pixels

**Comment by henryjameslau** [comment]
No way!
